# Generated by Django 5.0.4 on 2024-06-23 09:19
import random

from django.db import migrations


def add_barcodes(apps, schema_editor):
    Products = apps.get_model('main_app', 'Product')
    all_products = Products.objects.all()
    all_barcodes = random.sample(
        range(100_000_000, 1_000_000_000),
        len(all_products))
    for product, barcode in zip(all_products, all_barcodes):
        product.barcode = barcode
        product.save()


def reverse_barcodes(apps, schema_editor):
    Products = apps.get_model('main_app', 'Product')
    all_products = Products.objects.all()
    for p in all_products:
        p.barcode = 0
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_product_count_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RunPython(add_barcodes, reverse_code=reverse_barcodes)
        ]
