# Generated by Django 5.0.4 on 2024-06-24 20:37

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    Shoe = apps.get_model('main_app', 'Shoe')
    UniqueBrand = apps.get_model('main_app', 'UniqueBrands')

    unique_brand_names = Shoe.objects.values_list('brand', flat=True).distinct()

    UniqueBrand.objects.bulk_create(UniqueBrand(brand_name=brand_name) for brand_name in unique_brand_names)


def reverse_unique_brands(apps, schema_editor):
    UniqueBrand = apps.get_model('main_app', 'UniqueBrands')
    UniqueBrand.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_uniquebrands'),
    ]

    operations = [migrations.RunPython(create_unique_brands, reverse_code=reverse_unique_brands)
    ]
