# Generated by Django 5.0.4 on 2024-06-24 20:49

from django.db import migrations


def set_age_group(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')
    people = Person.objects.all()

    for person in people:
        if person.age <= 12:
            person.age_group = 'Child'
        elif person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'

    Person.objects.bulk_update(people, ['age_group'])


def remove_age_group(apps, schema_editor):
    Person = apps.get_model('main_app', 'Person')
    people = Person.objects.all()

    for person in people:
        person.age_group = Person._meta.get_field('age_group').default

    Person.objects.bulk_update(people, ['age_group'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_person'),
    ]

    operations = [migrations.RunPython(set_age_group, remove_age_group)
    ]
