# Generated by Django 5.0.4 on 2024-06-24 21:14

from django.db import migrations


def set_price(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    phones = Smartphone.objects.all()

    for phone in phones:
        phone.price = 120 * len(phone.brand)

    Smartphone.objects.bulk_update(phones, ['price'])


def set_category(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    phones = Smartphone.objects.all()

    for phone in phones:
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'

    Smartphone.objects.bulk_update(phones, ['category'])


def reverse_price_and_category(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    phones = Smartphone.objects.all()

    for phone in phones:
        phone.category = Smartphone._meta.get_field('category').default
        phone.price = Smartphone._meta.get_field('price').default
        phone.save()


def apply_functions(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_smartphone'),
    ]

    operations = [migrations.RunPython(apply_functions, reverse_price_and_category),
    ]
