# Generated by Django 5.0.4 on 2024-06-25 07:43

from django.db import migrations
from django.utils import timezone


def set_delivery_warranty(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    all_orders = Order.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        elif order.status == 'Cancelled':
            order.delete()


def reverse_delivery_warranty(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    all_orders = Order.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = Order._meta.get_field('warranty').default

        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order'),
    ]

    operations = [migrations.RunPython(set_delivery_warranty, reverse_delivery_warranty)
    ]
